Rename object to Object
Using Typescript 2.3.2, hit the following error:
    Error - typescript - node_modules\botframework-directlinejs\built\directLine.d.ts(203,12): error TS2304: Cannot find name 'object'.

Found the [following issue](https://github.com/Microsoft/TypeScript/issues/14647) on the Typescript repo that suggested using uppercase O due to the object keyword in Typescript 2.2. Changing this certainly fixed in my scenario.