Ignore errorConversationEnded on end()
It is expected to be thrown there.

Example:
directLine.activity$
.filter(activity => activity.type === 'message')
.subscribe(
    message => {
      console.log("received message ", message)
      directLine.end();
    }
);

/.../node_modules/botframework-directlinejs/node_modules/rxjs/Subscriber.js:246
            throw err;
            ^
Error: conversation ended
    at Object.<anonymous> (/.../node_modules/botframework-directlinejs/built/directLine.js:47:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/.../azure-bot.js:3:42)
    at Module._compile (internal/modules/cjs/loader.js:686:14)